# Generated by Django 5.0.6 on 2024-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_names',
            field=models.ManyToManyField(blank=True, related_name='predicted_users', to='users.role'),
        ),
    ]
