# Generated by Django 5.0.6 on 2024-07-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role_user_role_features_user_role_names'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_features',
            field=models.JSONField(blank=True, null=True, verbose_name='Role Features'),
        ),
    ]
