# Generated by Django 5.0.6 on 2024-07-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_user_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_features',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_names',
        ),
    ]
