# Generated by Django 5.0.6 on 2024-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
