# Generated by Django 5.0.6 on 2024-07-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='departement',
        ),
    ]
