# Generated by Django 5.0.6 on 2024-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_rename_amount_due_client_amount_remaining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='amount_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pieces_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
