# Generated by Django 5.0.6 on 2024-07-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_remove_client_amount_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
