# Generated by Django 5.0.6 on 2024-07-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_client_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
