# Generated by Django 5.0.6 on 2024-07-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_rename_phone_number_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pieces_purchased',
        ),
        migrations.AddField(
            model_name='client',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
