# Generated by Django 5.0.6 on 2024-07-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_remove_client_pieces_purchased_client_amount_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
