# Generated by Django 5.0.6 on 2024-07-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
