# Generated by Django 5.0.6 on 2024-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_client_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
