# Generated by Django 5.0.6 on 2024-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_client_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
