# Generated by Django 5.0.6 on 2024-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
