# Generated by Django 5.0.6 on 2024-07-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0014_alter_client_amount_remaining_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_signature_definitif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_signature_pv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='duree_garantie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='num_dossier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
