# Generated by Django 5.0.6 on 2024-07-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0017_document_description_alter_document_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='File',
        ),
    ]
