# Generated by Django 5.0.6 on 2024-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0018_rename_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images/'),
        ),
    ]
