# Generated by Django 5.0.6 on 2024-08-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fille',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiiles', to='marchands.marchand'),
        ),
        migrations.AlterField(
            model_name='fille',
            name='file',
            field=models.FileField(upload_to='upploads/'),
        ),
    ]
