# Generated by Django 5.0.6 on 2024-08-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchands', '0002_alter_fille_client_alter_fille_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchand',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
