# Generated by Django 5.0.6 on 2024-08-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchands', '0003_marchand_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fille',
            old_name='file',
            new_name='fille',
        ),
        migrations.RemoveField(
            model_name='fille',
            name='client',
        ),
        migrations.AddField(
            model_name='fille',
            name='marchand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichier', to='marchands.marchand'),
        ),
        migrations.AlterField(
            model_name='fille',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
