# Generated by Django 5.0.6 on 2024-08-22 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchands', '0004_rename_file_fille_fille_remove_fille_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marchand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='marchands.marchand')),
            ],
        ),
    ]
